# Generated by Django 4.2.30 on 2026-05-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0002_vitalslog_medication'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='meet_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='consultation',
            name='prescription_meds',
            field=models.TextField(blank=True, help_text='JSON list of prescribed medications'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='prescription_notes',
            field=models.TextField(blank=True, help_text="Doctor's notes for the prescription"),
        ),
        migrations.AddField(
            model_name='consultation',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
